/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apppersedianbarang;

/**
 *
 * @author Syara
 */
public class BarangMasuk extends javax.swing.JFrame {

    /**
     * Creates new form BarangMasuk
     */
    int xx, xy; //free mouse frame
    
    public BarangMasuk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_exit = new javax.swing.JButton();
        btn_maximize = new javax.swing.JButton();
        btn_minimize = new javax.swing.JButton();
        tx_idtransaksi = new javax.swing.JTextField();
        jdc_tanggalmasuk = new com.toedter.calendar.JDateChooser();
        tx_idbarang = new javax.swing.JTextField();
        tx_namabarang = new javax.swing.JTextField();
        tx_satuanbarang = new javax.swing.JTextField();
        tx_gudangbarang = new javax.swing.JTextField();
        tx_stockbarang = new javax.swing.JTextField();
        tx_stockbarangmasuk = new javax.swing.JTextField();
        tx_totalstockbarang = new javax.swing.JTextField();
        tx_hargabarang = new javax.swing.JTextField();
        tx_caribarang = new javax.swing.JTextField();
        tx_barangmasuk = new javax.swing.JTextField();
        tx_idbarang1 = new javax.swing.JTextField();
        tx_idtransaksi1 = new javax.swing.JTextField();
        tx_totaldata = new javax.swing.JTextField();
        tx_tanggalakhirlbarang = new javax.swing.JTextField();
        tx_tanggalawalbarang = new javax.swing.JTextField();
        btn_reset = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_tambahdata = new javax.swing.JButton();
        btn_idtransaksi = new javax.swing.JButton();
        btn_caridata = new javax.swing.JButton();
        btn_printdata = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setBackground(new java.awt.Color(0,0,0,1));
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, 20, 20));

        btn_maximize.setBackground(new java.awt.Color(0,0,0,1));
        btn_maximize.setBorder(null);
        btn_maximize.setBorderPainted(false);
        btn_maximize.setContentAreaFilled(false);
        btn_maximize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_maximizeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 10, 20));

        btn_minimize.setBackground(new java.awt.Color(0,0,0,1));
        btn_minimize.setBorder(null);
        btn_minimize.setBorderPainted(false);
        btn_minimize.setContentAreaFilled(false);
        btn_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 10, 20));

        tx_idtransaksi.setBackground(java.awt.Color.lightGray);
        tx_idtransaksi.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_idtransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        tx_idtransaksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_idtransaksiFocusGained(evt);
            }
        });
        tx_idtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_idtransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(tx_idtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 250, 50));

        jdc_tanggalmasuk.setBackground(java.awt.Color.lightGray);
        getContentPane().add(jdc_tanggalmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 230, 40));

        tx_idbarang.setBackground(java.awt.Color.lightGray);
        tx_idbarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_idbarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        tx_idbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_idbarangFocusGained(evt);
            }
        });
        tx_idbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_idbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_idbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 250, 50));

        tx_namabarang.setBackground(java.awt.Color.lightGray);
        tx_namabarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_namabarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        tx_namabarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_namabarangFocusGained(evt);
            }
        });
        tx_namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_namabarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 250, 50));

        tx_satuanbarang.setBackground(java.awt.Color.lightGray);
        tx_satuanbarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_satuanbarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        tx_satuanbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_satuanbarangFocusGained(evt);
            }
        });
        tx_satuanbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_satuanbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_satuanbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 250, 50));

        tx_gudangbarang.setBackground(java.awt.Color.lightGray);
        tx_gudangbarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_gudangbarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        tx_gudangbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_gudangbarangFocusGained(evt);
            }
        });
        tx_gudangbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_gudangbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_gudangbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 250, 50));

        tx_stockbarang.setBackground(java.awt.Color.lightGray);
        tx_stockbarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_stockbarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        tx_stockbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_stockbarangFocusGained(evt);
            }
        });
        tx_stockbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_stockbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_stockbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 70, 50));

        tx_stockbarangmasuk.setBackground(java.awt.Color.lightGray);
        tx_stockbarangmasuk.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_stockbarangmasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        tx_stockbarangmasuk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_stockbarangmasukFocusGained(evt);
            }
        });
        tx_stockbarangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_stockbarangmasukActionPerformed(evt);
            }
        });
        getContentPane().add(tx_stockbarangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 110, 50));

        tx_totalstockbarang.setBackground(java.awt.Color.lightGray);
        tx_totalstockbarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_totalstockbarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        tx_totalstockbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_totalstockbarangFocusGained(evt);
            }
        });
        tx_totalstockbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_totalstockbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_totalstockbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 250, 50));

        tx_hargabarang.setBackground(java.awt.Color.lightGray);
        tx_hargabarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_hargabarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        tx_hargabarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_hargabarangFocusGained(evt);
            }
        });
        tx_hargabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_hargabarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_hargabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 250, 50));

        tx_caribarang.setBorder(null);
        getContentPane().add(tx_caribarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, 200, 30));

        tx_barangmasuk.setBorder(null);
        getContentPane().add(tx_barangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 90, 30));

        tx_idbarang1.setBorder(null);
        getContentPane().add(tx_idbarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 90, 30));

        tx_idtransaksi1.setBorder(null);
        tx_idtransaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_idtransaksi1ActionPerformed(evt);
            }
        });
        getContentPane().add(tx_idtransaksi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 90, 30));

        tx_totaldata.setBorder(null);
        getContentPane().add(tx_totaldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 70, 30));

        tx_tanggalakhirlbarang.setBorder(null);
        getContentPane().add(tx_tanggalakhirlbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 730, 190, 20));

        tx_tanggalawalbarang.setBorder(null);
        getContentPane().add(tx_tanggalawalbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 730, 180, 20));

        btn_reset.setBackground(new java.awt.Color(0,0,0,1));
        btn_reset.setBorder(null);
        btn_reset.setBorderPainted(false);
        btn_reset.setContentAreaFilled(false);
        btn_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, 20));

        btn_update.setBackground(new java.awt.Color(0,0,0,1));
        btn_update.setBorder(null);
        btn_update.setBorderPainted(false);
        btn_update.setContentAreaFilled(false);
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 60, 20));

        btn_delete.setBackground(new java.awt.Color(0,0,0,1));
        btn_delete.setBorder(null);
        btn_delete.setBorderPainted(false);
        btn_delete.setContentAreaFilled(false);
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 60, 20));

        btn_tambahdata.setBackground(new java.awt.Color(0,0,0,1));
        btn_tambahdata.setBorder(null);
        btn_tambahdata.setBorderPainted(false);
        btn_tambahdata.setContentAreaFilled(false);
        btn_tambahdata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahdataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambahdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 60, 20));

        btn_idtransaksi.setBackground(new java.awt.Color(0,0,0,1));
        btn_idtransaksi.setBorder(null);
        btn_idtransaksi.setBorderPainted(false);
        btn_idtransaksi.setContentAreaFilled(false);
        btn_idtransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_idtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idtransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_idtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 20));

        btn_caridata.setBackground(new java.awt.Color(0,0,0,1));
        btn_caridata.setBorder(null);
        btn_caridata.setBorderPainted(false);
        btn_caridata.setContentAreaFilled(false);
        btn_caridata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_caridata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caridataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_caridata, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 720, 120, 30));

        btn_printdata.setBackground(new java.awt.Color(0,0,0,1));
        btn_printdata.setBorder(null);
        btn_printdata.setBorderPainted(false);
        btn_printdata.setContentAreaFilled(false);
        btn_printdata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_printdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printdataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_printdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 720, 120, 30));

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/BG_Barang Masuk.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximizeMouseClicked
        if (this.getExtendedState()!=BarangMasuk.MAXIMIZED_BOTH){
            this.setExtendedState(BarangMasuk.MAXIMIZED_BOTH);
        }else {
            this.setExtendedState(BarangMasuk.NORMAL);
        }
    }//GEN-LAST:event_btn_maximizeMouseClicked

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        this.setState(BarangMasuk.ICONIFIED);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void tx_idtransaksiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_idtransaksiFocusGained
        String pass=tx_idtransaksi.getText();
        if(pass.equals("password")){
            tx_idtransaksi.setText("");
        }
    }//GEN-LAST:event_tx_idtransaksiFocusGained

    private void tx_idtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_idtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idtransaksiActionPerformed

    private void tx_idbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_idbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idbarangFocusGained

    private void tx_idbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_idbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idbarangActionPerformed

    private void tx_namabarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_namabarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_namabarangFocusGained

    private void tx_namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_namabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_namabarangActionPerformed

    private void tx_gudangbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_gudangbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_gudangbarangFocusGained

    private void tx_gudangbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_gudangbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_gudangbarangActionPerformed

    private void tx_satuanbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_satuanbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_satuanbarangFocusGained

    private void tx_satuanbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_satuanbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_satuanbarangActionPerformed

    private void tx_stockbarangmasukFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_stockbarangmasukFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_stockbarangmasukFocusGained

    private void tx_stockbarangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_stockbarangmasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_stockbarangmasukActionPerformed

    private void tx_stockbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_stockbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_stockbarangFocusGained

    private void tx_stockbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_stockbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_stockbarangActionPerformed

    private void tx_totalstockbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_totalstockbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_totalstockbarangFocusGained

    private void tx_totalstockbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_totalstockbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_totalstockbarangActionPerformed

    private void tx_hargabarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_hargabarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_hargabarangFocusGained

    private void tx_hargabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_hargabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_hargabarangActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    xx = evt.getX();
    xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btn_idtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idtransaksiActionPerformed

    }//GEN-LAST:event_btn_idtransaksiActionPerformed

    private void btn_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tambahdataActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_printdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_printdataActionPerformed

    private void btn_caridataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caridataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_caridataActionPerformed

    private void tx_idtransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_idtransaksi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idtransaksi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_caridata;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_idtransaksi;
    private javax.swing.JButton btn_maximize;
    private javax.swing.JButton btn_minimize;
    private javax.swing.JButton btn_printdata;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambahdata;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser jdc_tanggalmasuk;
    private javax.swing.JTextField tx_barangmasuk;
    private javax.swing.JTextField tx_caribarang;
    private javax.swing.JTextField tx_gudangbarang;
    private javax.swing.JTextField tx_hargabarang;
    private javax.swing.JTextField tx_idbarang;
    private javax.swing.JTextField tx_idbarang1;
    private javax.swing.JTextField tx_idtransaksi;
    private javax.swing.JTextField tx_idtransaksi1;
    private javax.swing.JTextField tx_namabarang;
    private javax.swing.JTextField tx_satuanbarang;
    private javax.swing.JTextField tx_stockbarang;
    private javax.swing.JTextField tx_stockbarangmasuk;
    private javax.swing.JTextField tx_tanggalakhirlbarang;
    private javax.swing.JTextField tx_tanggalawalbarang;
    private javax.swing.JTextField tx_totaldata;
    private javax.swing.JTextField tx_totalstockbarang;
    // End of variables declaration//GEN-END:variables
}
