/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apppersedianbarang;

/**
 *
 * @author Syara
 */
public class BarangMasuk extends javax.swing.JFrame {

    /**
     * Creates new form BarangMasuk
     */
    int xx, xy; //free mouse frame
    
    public BarangMasuk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_exit = new javax.swing.JButton();
        btn_maximize = new javax.swing.JButton();
        btn_minimize = new javax.swing.JButton();
        tx_idtransaksi = new javax.swing.JTextField();
        jdc_tanggalmasuk = new com.toedter.calendar.JDateChooser();
        tx_tanggalmasuk = new javax.swing.JTextField();
        tx_idbarang = new javax.swing.JTextField();
        tx_namabarang = new javax.swing.JTextField();
        tx_satuanbarang = new javax.swing.JTextField();
        tx_gudangbarang = new javax.swing.JTextField();
        tx_stockbarang = new javax.swing.JTextField();
        tx_stockbarangmasuk = new javax.swing.JTextField();
        tx_totalstockbarang = new javax.swing.JTextField();
        tx_hargabarang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setBackground(new java.awt.Color(0,0,0,1));
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, 20, 20));

        btn_maximize.setBackground(new java.awt.Color(0,0,0,1));
        btn_maximize.setBorder(null);
        btn_maximize.setBorderPainted(false);
        btn_maximize.setContentAreaFilled(false);
        btn_maximize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_maximizeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 10, 20));

        btn_minimize.setBackground(new java.awt.Color(0,0,0,1));
        btn_minimize.setBorder(null);
        btn_minimize.setBorderPainted(false);
        btn_minimize.setContentAreaFilled(false);
        btn_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 10, 20));

        tx_idtransaksi.setBackground(java.awt.Color.lightGray);
        tx_idtransaksi.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_idtransaksi.setBorder(null);
        tx_idtransaksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_idtransaksiFocusGained(evt);
            }
        });
        tx_idtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_idtransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(tx_idtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 250, 50));

        jdc_tanggalmasuk.setBackground(java.awt.Color.lightGray);
        getContentPane().add(jdc_tanggalmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 250, 40));

        tx_tanggalmasuk.setBackground(java.awt.Color.lightGray);
        tx_tanggalmasuk.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_tanggalmasuk.setBorder(null);
        tx_tanggalmasuk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_tanggalmasukFocusGained(evt);
            }
        });
        tx_tanggalmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_tanggalmasukActionPerformed(evt);
            }
        });
        getContentPane().add(tx_tanggalmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 250, 40));

        tx_idbarang.setBackground(java.awt.Color.lightGray);
        tx_idbarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_idbarang.setBorder(null);
        tx_idbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_idbarangFocusGained(evt);
            }
        });
        tx_idbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_idbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_idbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 250, 50));

        tx_namabarang.setBackground(java.awt.Color.lightGray);
        tx_namabarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_namabarang.setBorder(null);
        tx_namabarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_namabarangFocusGained(evt);
            }
        });
        tx_namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_namabarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 250, 40));

        tx_satuanbarang.setBackground(java.awt.Color.lightGray);
        tx_satuanbarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_satuanbarang.setBorder(null);
        tx_satuanbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_satuanbarangFocusGained(evt);
            }
        });
        tx_satuanbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_satuanbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_satuanbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 250, 50));

        tx_gudangbarang.setBackground(java.awt.Color.lightGray);
        tx_gudangbarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_gudangbarang.setBorder(null);
        tx_gudangbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_gudangbarangFocusGained(evt);
            }
        });
        tx_gudangbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_gudangbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_gudangbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 250, 40));

        tx_stockbarang.setBackground(java.awt.Color.lightGray);
        tx_stockbarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_stockbarang.setBorder(null);
        tx_stockbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_stockbarangFocusGained(evt);
            }
        });
        tx_stockbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_stockbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_stockbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 570, -1, 40));

        tx_stockbarangmasuk.setBackground(java.awt.Color.lightGray);
        tx_stockbarangmasuk.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_stockbarangmasuk.setBorder(null);
        tx_stockbarangmasuk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_stockbarangmasukFocusGained(evt);
            }
        });
        tx_stockbarangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_stockbarangmasukActionPerformed(evt);
            }
        });
        getContentPane().add(tx_stockbarangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 110, 50));

        tx_totalstockbarang.setBackground(java.awt.Color.lightGray);
        tx_totalstockbarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_totalstockbarang.setBorder(null);
        tx_totalstockbarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_totalstockbarangFocusGained(evt);
            }
        });
        tx_totalstockbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_totalstockbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_totalstockbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 250, 40));

        tx_hargabarang.setBackground(java.awt.Color.lightGray);
        tx_hargabarang.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_hargabarang.setBorder(null);
        tx_hargabarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_hargabarangFocusGained(evt);
            }
        });
        tx_hargabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_hargabarangActionPerformed(evt);
            }
        });
        getContentPane().add(tx_hargabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 680, 250, 40));

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximizeMouseClicked
        if (this.getExtendedState()!=BarangMasuk.MAXIMIZED_BOTH){
            this.setExtendedState(BarangMasuk.MAXIMIZED_BOTH);
        }else {
            this.setExtendedState(BarangMasuk.NORMAL);
        }
    }//GEN-LAST:event_btn_maximizeMouseClicked

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        this.setState(BarangMasuk.ICONIFIED);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void tx_idtransaksiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_idtransaksiFocusGained
        String pass=tx_idtransaksi.getText();
        if(pass.equals("password")){
            tx_idtransaksi.setText("");
        }
    }//GEN-LAST:event_tx_idtransaksiFocusGained

    private void tx_idtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_idtransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idtransaksiActionPerformed

    private void tx_tanggalmasukFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_tanggalmasukFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_tanggalmasukFocusGained

    private void tx_tanggalmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_tanggalmasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_tanggalmasukActionPerformed

    private void tx_idbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_idbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idbarangFocusGained

    private void tx_idbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_idbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idbarangActionPerformed

    private void tx_namabarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_namabarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_namabarangFocusGained

    private void tx_namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_namabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_namabarangActionPerformed

    private void tx_gudangbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_gudangbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_gudangbarangFocusGained

    private void tx_gudangbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_gudangbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_gudangbarangActionPerformed

    private void tx_satuanbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_satuanbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_satuanbarangFocusGained

    private void tx_satuanbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_satuanbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_satuanbarangActionPerformed

    private void tx_stockbarangmasukFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_stockbarangmasukFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_stockbarangmasukFocusGained

    private void tx_stockbarangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_stockbarangmasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_stockbarangmasukActionPerformed

    private void tx_stockbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_stockbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_stockbarangFocusGained

    private void tx_stockbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_stockbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_stockbarangActionPerformed

    private void tx_totalstockbarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_totalstockbarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_totalstockbarangFocusGained

    private void tx_totalstockbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_totalstockbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_totalstockbarangActionPerformed

    private void tx_hargabarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_hargabarangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_hargabarangFocusGained

    private void tx_hargabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_hargabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_hargabarangActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    xx = evt.getX();
    xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_maximize;
    private javax.swing.JButton btn_minimize;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser jdc_tanggalmasuk;
    private javax.swing.JTextField tx_gudangbarang;
    private javax.swing.JTextField tx_hargabarang;
    private javax.swing.JTextField tx_idbarang;
    private javax.swing.JTextField tx_idtransaksi;
    private javax.swing.JTextField tx_namabarang;
    private javax.swing.JTextField tx_satuanbarang;
    private javax.swing.JTextField tx_stockbarang;
    private javax.swing.JTextField tx_stockbarangmasuk;
    private javax.swing.JTextField tx_tanggalmasuk;
    private javax.swing.JTextField tx_totalstockbarang;
    // End of variables declaration//GEN-END:variables
}
