/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apppersedianbarang;
import com.sun.jdi.connect.spi.Connection;
//import java.beans.Statement;Statement
import java.io.ObjectInputFilter.Config;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class Tampilanlogin extends javax.swing.JFrame {                                                                                                                                                                                                                 
int xx, xy;
    
    
    /**
     * Creates new form Login
     */
    private java.sql.Connection conn;
    
    public Tampilanlogin() {
     initComponents();
        conn = koneksi.getConnection();
    }

    void bersih(){
        tx_username.setText("username");
        tx_password.setText("password");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tx_password = new javax.swing.JPasswordField();
        tx_username = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_minimaze = new javax.swing.JButton();
        btn_maximize = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tx_password.setText("jPasswordField1");
        tx_password.setBorder(null);
        getContentPane().add(tx_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 492, 280, 30));

        tx_username.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tx_username.setText("username");
        tx_username.setBorder(null);
        tx_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_usernameFocusGained(evt);
            }
        });
        tx_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(tx_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 418, 280, 30));

        btn_login.setBackground(new java.awt.Color(0,0,0,1));
        btn_login.setBorder(null);
        btn_login.setBorderPainted(false);
        btn_login.setContentAreaFilled(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 160, 50));

        btn_exit.setBackground(new java.awt.Color(0,0,0,1));
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 20, 20));

        btn_minimaze.setBackground(new java.awt.Color(0,0,0,1));
        btn_minimaze.setBorder(null);
        btn_minimaze.setBorderPainted(false);
        btn_minimaze.setContentAreaFilled(false);
        btn_minimaze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimaze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimazeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_minimaze, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 20, 20));

        btn_maximize.setBackground(new java.awt.Color(0,0,0,1));
        btn_maximize.setBorder(null);
        btn_maximize.setBorderPainted(false);
        btn_maximize.setContentAreaFilled(false);
        btn_maximize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_maximizeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 20, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/BG_Login.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tx_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_usernameActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    xx = evt.getX();
    xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void tx_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_usernameFocusGained
    String pass=tx_username.getText();
    if(pass.equals("username")){
        tx_username.setText("");
    }
    }//GEN-LAST:event_tx_usernameFocusGained

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
    try{
         String sql = "SELECT * FROM login WHERE username=('"+tx_username.getText()+"')AND password=('"+tx_password.getText()+"')";
         PreparedStatement st = conn.prepareStatement(sql);
         ResultSet rs = st.executeQuery();
         java.sql.PreparedStatement pst=conn.prepareStatement(sql);
         if (rs.next()){
                if(tx_username.getText().equals(rs.getString("username"))&& tx_password.getText().equals(rs.getString("password"))){
                   JOptionPane.showMessageDialog(null,"Berhasil Login");
                   this.setVisible(false);
                   new TampilanMenu().setVisible(true);
                }
         } else{
             JOptionPane.showMessageDialog(null,"username atau password salah");
         }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this,e.getMessage());
     }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_minimazeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimazeMouseClicked
    this.setState(Tampilanlogin.ICONIFIED);
    }//GEN-LAST:event_btn_minimazeMouseClicked

    private void btn_maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximizeMouseClicked
    if (this.getExtendedState()!=Tampilanlogin.MAXIMIZED_BOTH){
        this.setExtendedState(Tampilanlogin.MAXIMIZED_BOTH);
    }else {
            this.setExtendedState(Tampilanlogin.NORMAL);
        }
    }//GEN-LAST:event_btn_maximizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilanlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilanlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilanlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilanlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilanlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_maximize;
    private javax.swing.JButton btn_minimaze;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField tx_password;
    private javax.swing.JTextField tx_username;
    // End of variables declaration//GEN-END:variables
}
