/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apppersedianbarang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class TampilanMenu extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;
    String sql;
    /**
     * Creates new form TampilanMenu
     */
    
    int xx, xy; //free mouse frame
    
    public TampilanMenu() {
        initComponents();
        try{
        koneksi DB = new koneksi();
        DB.getConnection();
        con = DB.conn;
        stmt = DB.stm;
        String query = "SELECT * FROM tb_databarang";
            rs = stmt.executeQuery(query);
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("id");
            model.addColumn("Barang");
            model.addColumn("Jenis");
            model.addColumn("Satuan");
            model.addColumn("Gudang");
            model.addColumn("Stok");
            model.addColumn("Harga");
            model.addColumn("TotalBarang");

            while (rs.next()) {
                Object[] row = new Object[8];
                row[0] = rs.getInt("idbarang");
                row[1] = rs.getString("NamaBarang");
                row[2] = rs.getString("JenisBarang");
                row[3] = rs.getString("Satuan");
                row[4] = rs.getString("Gudang");
                row[5] = rs.getInt("Stok");
                row[6] = rs.getString("Harga");
                row[7] = rs.getString("TotalHarga");

                model.addRow(row);
            }
            TableBarang.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_minimize = new javax.swing.JButton();
        btn_maximize = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBarang = new javax.swing.JTable();
        btn_databarang = new javax.swing.JButton();
        btn_barangmasuk = new javax.swing.JButton();
        btn_barangkeluar = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_keluar2 = new javax.swing.JButton();
        btn_updatedata = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimize.setBackground(new java.awt.Color(0,0,0,1));
        btn_minimize.setBorder(null);
        btn_minimize.setBorderPainted(false);
        btn_minimize.setContentAreaFilled(false);
        btn_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 20, 20));

        btn_maximize.setBackground(new java.awt.Color(0,0,0,1));
        btn_maximize.setBorder(null);
        btn_maximize.setBorderPainted(false);
        btn_maximize.setContentAreaFilled(false);
        btn_maximize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_maximizeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 20, 20));

        btn_exit.setBackground(new java.awt.Color(0,0,0,1));
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 20, 20));

        TableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 750, 400));

        btn_databarang.setBackground(new java.awt.Color(0,0,0,1));
        btn_databarang.setBorder(null);
        btn_databarang.setBorderPainted(false);
        btn_databarang.setContentAreaFilled(false);
        btn_databarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_databarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_databarangMouseClicked(evt);
            }
        });
        getContentPane().add(btn_databarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, 30));

        btn_barangmasuk.setBackground(new java.awt.Color(0,0,0,1));
        btn_barangmasuk.setBorder(null);
        btn_barangmasuk.setBorderPainted(false);
        btn_barangmasuk.setContentAreaFilled(false);
        btn_barangmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_barangmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_barangmasukMouseClicked(evt);
            }
        });
        getContentPane().add(btn_barangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 160, 30));

        btn_barangkeluar.setBackground(new java.awt.Color(0,0,0,1));
        btn_barangkeluar.setBorder(null);
        btn_barangkeluar.setBorderPainted(false);
        btn_barangkeluar.setContentAreaFilled(false);
        btn_barangkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_barangkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_barangkeluarMouseClicked(evt);
            }
        });
        getContentPane().add(btn_barangkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 180, 30));

        btn_simpan.setBackground(new java.awt.Color(0,0,0,1));
        btn_simpan.setBorder(null);
        btn_simpan.setBorderPainted(false);
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 110, 30));

        btn_keluar2.setBackground(new java.awt.Color(0,0,0,1));
        btn_keluar2.setBorder(null);
        btn_keluar2.setBorderPainted(false);
        btn_keluar2.setContentAreaFilled(false);
        btn_keluar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_keluar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_keluar2MouseClicked(evt);
            }
        });
        getContentPane().add(btn_keluar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 110, 30));

        btn_updatedata.setBackground(new java.awt.Color(0,0,0,1));
        btn_updatedata.setBorder(null);
        btn_updatedata.setBorderPainted(false);
        btn_updatedata.setContentAreaFilled(false);
        btn_updatedata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updatedata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updatedataMouseClicked(evt);
            }
        });
        getContentPane().add(btn_updatedata, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 750, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg/BG_App Persediaan.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
    dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_databarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_databarangMouseClicked
    new DataBarang ().setVisible(true);
    }//GEN-LAST:event_btn_databarangMouseClicked

    private void btn_barangmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangmasukMouseClicked
    new BarangMasuk ().setVisible(true);
    }//GEN-LAST:event_btn_barangmasukMouseClicked

    private void btn_barangkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangkeluarMouseClicked
    new BarangKeluar ().setVisible(true);
    }//GEN-LAST:event_btn_barangkeluarMouseClicked

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
    this.setState(TampilanMenu.ICONIFIED);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void btn_maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximizeMouseClicked
    if (this.getExtendedState()!=TampilanMenu.MAXIMIZED_BOTH){
        this.setExtendedState(TampilanMenu.MAXIMIZED_BOTH);
    }else {
            this.setExtendedState(TampilanMenu.NORMAL);
        }
    }//GEN-LAST:event_btn_maximizeMouseClicked

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void btn_keluar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluar2MouseClicked
    dispose ();
    }//GEN-LAST:event_btn_keluar2MouseClicked

    private void btn_updatedataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updatedataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updatedataMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
     xx = evt.getX();
    xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableBarang;
    private javax.swing.JButton btn_barangkeluar;
    private javax.swing.JButton btn_barangmasuk;
    private javax.swing.JButton btn_databarang;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_keluar2;
    private javax.swing.JButton btn_maximize;
    private javax.swing.JButton btn_minimize;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_updatedata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
